"""Behavior tests for the propagated Graphify SVG cleaning helper."""

# Standard Library
import sys
import pathlib

# PIP3 modules
import lxml.etree

# local repo modules
import file_utils


# OWASP ASVS 5.0.0 V5.3.2: this fixed path uses trusted, internal components.
# pytest.ini is template-meta and never propagates, but this test does, so the
# devel/ directory is placed on sys.path here rather than relying on the
# template's pythonpath setting.
DEVEL_DIR: pathlib.Path = pathlib.Path(file_utils.get_repo_root()) / "devel"
if str(DEVEL_DIR) not in sys.path:
	sys.path.insert(0, str(DEVEL_DIR))

import graphify_clean_svg


SVG_NAMESPACE = "http://www.w3.org/2000/svg"


#============================================


def parse_svg(svg_text: str) -> lxml.etree._Element:
	"""Parse one inline SVG fixture and return its root element."""
	root = lxml.etree.fromstring(svg_text.encode("utf-8"))
	return root


#============================================


def labelled_svg() -> str:
	"""Return labels where the legend reuses a glyph defined by a node label."""
	svg_text = (
		f'<svg xmlns="{SVG_NAMESPACE}" xmlns:xlink="http://www.w3.org/1999/xlink">'
		'<g id="axes_1">'
		'<g id="text_1">'
		'<defs><path id="glyph_shared" d="M0 0 L1 1"/></defs>'
		'<use xlink:href="#glyph_shared"/>'
		'</g>'
		'</g>'
		'<g id="legend_1">'
		'<g id="text_2"><use xlink:href="#glyph_shared"/></g>'
		'</g>'
		'</svg>'
	)
	return svg_text


#============================================


def test_legend_labels_survive_and_node_labels_do_not() -> None:
	"""Community names stay; the per-node filename labels are what go."""
	root = parse_svg(labelled_svg())
	graphify_clean_svg.remove_node_labels(root)
	remaining_ids = {
		graphify_clean_svg.element_id(element)
		for element in root.iter()
		if graphify_clean_svg.is_element(element)
	}
	assert remaining_ids & {"text_1", "text_2", "glyph_shared"} == {
		"text_2", "glyph_shared",
	}
	assert graphify_clean_svg.unresolved_reference_ids(root) == set()


#============================================


def test_a_comment_node_does_not_break_the_walk() -> None:
	"""lxml yields comments whose get() returns None whatever default is given."""
	svg_text = (
		f'<svg xmlns="{SVG_NAMESPACE}">'
		'<!-- generated by matplotlib -->'
		'<g id="axes_1"><g id="text_1"><use x="1"/></g></g>'
		'</svg>'
	)
	root = parse_svg(svg_text)
	removed = graphify_clean_svg.remove_node_labels(root)
	assert removed == 1


#============================================


def test_unreferenced_definitions_are_collected() -> None:
	"""A top-level definition nothing points at is dead weight."""
	svg_text = (
		f'<svg xmlns="{SVG_NAMESPACE}">'
		'<defs><path id="glyph_live" d="M0 0"/><path id="glyph_dead" d="M1 1"/></defs>'
		'<use xlink:href="#glyph_live" xmlns:xlink="http://www.w3.org/1999/xlink"/>'
		'</svg>'
	)
	root = parse_svg(svg_text)
	graphify_clean_svg.remove_dead_definitions(root)
	remaining_ids = {
		graphify_clean_svg.element_id(element)
		for element in root.iter()
		if graphify_clean_svg.is_element(element)
	}
	assert remaining_ids & {"glyph_live", "glyph_dead"} == {"glyph_live"}


#============================================


def test_clip_paths_referenced_by_url_are_not_collected() -> None:
	"""Clip paths are reached through url(#id), not href, and must survive."""
	svg_text = (
		f'<svg xmlns="{SVG_NAMESPACE}">'
		'<defs><clipPath id="clip_live"><path d="M0 0"/></clipPath></defs>'
		'<g clip-path="url(#clip_live)"><path d="M2 2"/></g>'
		'</svg>'
	)
	root = parse_svg(svg_text)
	graphify_clean_svg.remove_dead_definitions(root)
	remaining_ids = {
		graphify_clean_svg.element_id(element)
		for element in root.iter()
		if graphify_clean_svg.is_element(element)
	}
	assert "clip_live" in remaining_ids


#============================================


def test_rounding_keeps_path_commands_intact() -> None:
	"""Only numeric tokens are rewritten; command letters are untouched."""
	rounded = graphify_clean_svg.round_number_text("M 1.234567 L 2.987654 z")
	assert rounded == "M 1.23 L 2.99 z"

# Vendored pytest file. Local changes can and will be overwritten.
